### ISSUE TITLE
chrome-color-picker (1 deprecation)

### ISSUE THREAD

**Issue by so53neil** [puranjayjain/chrome-color-picker#21]
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using shadowRoot and access the editor contents directly instead.

HTMLElement.shadowRoot - /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:13:10
Object.toggle - /Users/#/.atom/packages/chrome-color-picker/lib/chrome-color-picker.coffee:244:42
HTMLElement.subscriptions.add.atom.commands.add.chrome-color-picker:toggle - /Users/#/.atom/packages/chrome-color-picker/lib/chrome-color-picker.coffee:117:26
CommandRegistry.handleCommandEvent - <embedded>:22450:36
CommandRegistry.dispatch - <embedded>:22335:23
AtomEnvironment.dispatchContextMenuCommand - <embedded>:1626:34k:

**Comment by rrroyal** [comment]
Fixed in #24.

**Comment by ghost** [comment]
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using shadowRoot and access the editor contents directly instead.

HTMLElement.shadowRoot - /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:13:10
Object.toggle - /Users/#/.atom/packages/chrome-color-picker/lib/chrome-color-picker.coffee:244:42
HTMLElement.subscriptions.add.atom.commands.add.chrome-color-picker:toggle - /Users/#/.atom/packages/chrome-color-picker/lib/chrome-color-picker.coffee:117:26
CommandRegistry.handleCommandEvent - :22450:36
CommandRegistry.dispatch - :22335:23
AtomEnvironment.dispatchContextMenuCommand - :1626:34k:

**Comment by puranjayjain** [comment]
@LuVerdini can you raise a PR request for this ?
