### ISSUE TITLE
Hex code capitalization is not enforced.

### ISSUE THREAD

**Issue by VishwaJay** [puranjayjain/chrome-color-picker#23]
The setting to enforce capital letters in hex codes does not enforce capitals. However, the rest of the package is well-done, even with the deprecated calls.

If requested, I can offer screen shots. However, this seems very straightforward.

**Comment by puranjayjain** [comment]
Please add some screenshots that might be helpful

**Comment by VishwaJay** [comment]
![Showing the hex code](https://user-images.githubusercontent.com/3241421/59457229-4368c180-8dd5-11e9-851d-fdfb9c217aa0.png)
![After I tap "enter"](https://user-images.githubusercontent.com/3241421/59457230-4368c180-8dd5-11e9-84f2-932d2558df55.png)
![Settings](https://user-images.githubusercontent.com/3241421/59457231-4368c180-8dd5-11e9-909f-e735adc1338c.png)

Hope these are helpful and illustrative.

**Comment by VishwaJay** [comment]
Sorry, redoing the second, since it covered exactly what I wanted to show...

**Comment by VishwaJay** [comment]
![Showing the result](https://user-images.githubusercontent.com/3241421/59457555-e0c3f580-8dd5-11e9-8650-6130da729494.png)

**Comment by VishwaJay** [comment]
Over 3 years later, and not even a comment. 

I've moved on, and Atom is in sunset. This won't be fixed.

**Comment by puranjayjain** [comment]
Sorry for not replying earlier. @VishwaJay I'm no longer actively maintaining this as I myself don't use atom anymore. I tried to do a migration for vscode but unfortunately it's not that straightforward to migrate to vscode. So this will remain as a placeholder.

**Comment by VishwaJay** [comment]
I can understand. No worries! I just like to make sure things are taken care of.
